#!/usr/bin/env python3
"""Generate docs/transcript.md and docs/audit-trail.md from a live run.

Requires the seeded stack running (make seed && make dev, or the agents on
ports 8101/8102). Runs Scenario A through both agents and writes the two
documents the submission needs: a sample reasoning transcript and a one-page
audit trail.
"""
import json
import sys
import urllib.request

COMM = "http://127.0.0.1:8101"
FAC = "http://127.0.0.1:8102"


def post(url: str, body: dict) -> dict:
    req = urllib.request.Request(
        url,
        data=json.dumps(body).encode(),
        headers={"content-type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return json.loads(r.read())


def get(url: str) -> dict:
    with urllib.request.urlopen(url, timeout=30) as r:
        return json.loads(r.read())


def get_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read().decode()


VISIT = {
    "mother": {"id": "M-AMINA", "age": 27, "gravida": 2, "para": 1},
    "ga_weeks": 34,
    "at": "2026-10-02T21:40",
    "readings": [
        {"kind": "sbp", "value": 152},
        {"kind": "dbp", "value": 98},
        {"kind": "sbp", "value": 150, "repeated": True},
        {"kind": "dbp", "value": 96, "repeated": True},
    ],
    "signs": [
        {"name": "severe-headache", "status": "present", "source": "chp"},
        {"name": "visual-disturbance", "status": "present", "source": "chp"},
    ],
}

FACILITY = {
    "at": "2026-10-02T23:30",
    "readings": [
        {"kind": "sbp", "value": 138},
        {"kind": "dbp", "value": 88},
        {"kind": "sbp", "value": 148, "repeated": True},
        {"kind": "dbp", "value": 96, "repeated": True},
        {"kind": "protein", "value": 2, "repeated": True},
    ],
    "treatment": "nifedipine-oral",
    "treatment_at": "2026-10-02T22:50",
}


def main() -> None:
    edge = post(f"{COMM}/visits", VISIT)
    ref = edge["referral_id"]
    post(f"{COMM}/connectivity", {"online": True})
    full = post(f"{FAC}/encounters", dict(FACILITY, referral_id=ref))
    rec = full["reconciled"]
    diff = full["diff"]
    for pid in ["severe-headache", "visual-disturbance"]:
        full = post(
            f"{FAC}/referrals/{ref}/contest",
            {"premise_id": pid,
             "reason": "symptom resolved after paracetamol",
             "by": "nurse-baraka"},
        )
    after = full["reconciled"]

    edge_d = edge["decision"]
    facility_log = get(f"{FAC}/memory/log?limit=40")["events"]
    raw_log = get_text(f"{FAC}/memory/export")

    transcript = f"""# Sample Reasoning Transcript: Scenario A (Amina)

> Generated by `scripts/export-transcript.py` from a live run of both agents.
> Every truth value below was computed by Omega's `lib_nal.metta` on PeTTa.

## 1. Community side, offline (21:40)

The CHP records BP 152/98, repeated 150/96 after 15 minutes rest, with a
severe headache and blurred vision. The community agent decides with the
edge pack (`{edge_d["pack"]}`), offline:

- **Level:** {edge_d["level"]} ({edge_d["band"]})
- **Rule:** `{edge_d["rule"]["id"]}` ({edge_d["rule"]["pack"]})
- **Conclusion:** {edge_d["conclusion"]} `(stv {edge_d["truth"]["f"]:.5f} {edge_d["truth"]["c"]:.5f})`

Verbatim NAL proof term from Omega:

```metta
{edge_d["proof_raw"]}
```

English:
{chr(10).join(f"- {l}" for l in edge_d["explanation_en"])}

Swahili:
{chr(10).join(f"- {l}" for l in edge_d["explanation_sw"])}

The referral is queued: "Will sync when connection returns."

## 2. Connectivity returns (22:55)

The packet syncs to the facility agent (`/sync`, idempotent by packet id).

## 3. Facility side, reconciliation (23:30)

The nurse records arrival BP 138/88 at 23:30 (40 minutes after oral
nifedipine), the repeat 148/96 at 23:50, and dipstick protein 2+. The
facility agent remembers Amina's 14-week visit (BP 116/74).

- **Level:** {rec["level"]} ({rec["band"]})
- **Rule:** `{rec["rule"]["id"]}` ({rec["rule"]["pack"]})
- **Conclusion:** {rec["conclusion"]} `(stv {rec["truth"]["f"]:.5f} {rec["truth"]["c"]:.5f})`

Verbatim NAL proof term:

```metta
{rec["proof_raw"]}
```

### The diff (what changed and why)

| Change | Reason |
|---|---|
{chr(10).join(f"| `{c['type']}` | {c['reason_en']} |" for c in diff["changes"])}

## 4. Contest

The nurse withdraws the severe headache ("resolved after paracetamol") and
then the visual disturbance. The decision recomputes:

- **Level:** {after["level"]} via rule `{after["rule"]["id"]}`
  (pre-eclampsia from new onset plus proteinuria, no severe feature left)

Both withdrawals are atoms in the log with who and why.

## 5. The audit trail (facility agent, append-only)

```metta
{raw_log}
```
"""

    audit = f"""# Audit Trail: Amina's Referral (One Page)

> Generated by `scripts/export-transcript.py`. Every mutation the facility
> agent made for referral `{ref}`, newest last.

## Who did what, when

| N | Time | Op | Atom |
|---|---|---|---|
{chr(10).join(f"| {e['n']} | {e['ts']} | {e['op']} | `{e['atom']}` |" for e in reversed(facility_log))}

## Decisions on record

1. **Community (edge-v1):** {edge_d["level"]} via `{edge_d["rule"]["id"]}`,
   `(stv {edge_d["truth"]["f"]:.4f} {edge_d["truth"]["c"]:.4f})`, {edge_d["created_at"]}.
2. **Facility reconciled (full-v1):** {rec["level"]} via `{rec["rule"]["id"]}`,
   `(stv {rec["truth"]["f"]:.4f} {rec["truth"]["c"]:.4f})`, {rec["created_at"]}.
3. **After contest:** urgent via `r_pe` (premises withdrawn by nurse-baraka,
   reasons in the log above).

## Why this is tamper-evident

The log is append-only; the agent replays it on startup. Removing or editing
a past event changes every decision derived from it on replay, which is
visible on the next reconcile.
"""

    with open("docs/transcript.md", "w") as f:
        f.write(transcript)
    with open("docs/audit-trail.md", "w") as f:
        f.write(audit)
    print("wrote docs/transcript.md and docs/audit-trail.md")


if __name__ == "__main__":
    sys.exit(main())
